// This file is generated by @kysoql/codegen. Do not edit manually.

import type {
  SalesforceChildRelationship,
  SalesforceField,
  SalesforceObject,
  SalesforceParentRelationship,
} from "@kysoql/core";

export interface FilteredSchema {
  readonly "Account": SalesforceObject<
    {
      readonly "Id": SalesforceField<
        string,
        {
          readonly salesforceType: "id";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly aggregatable: true;
        }
      >;
      readonly "Name": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly aggregatable: true;
        }
      >;
      readonly "OwnerId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "User";
          readonly relationshipName: "Owner";
          readonly aggregatable: true;
        }
      >;
    },
    {
      readonly "Owner": SalesforceParentRelationship<
        "User",
        "OwnerId",
        false
      >;
    },
    {
      readonly "Contacts": SalesforceChildRelationship<
        "Contact",
        "AccountId"
      >;
    },
    "mine",
    Record<string, never>,
    true,
    "none",
    false
  >;
  readonly "Contact": SalesforceObject<
    {
      readonly "AccountId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "Account";
          readonly relationshipName: "Account";
          readonly aggregatable: true;
        }
      >;
      readonly "Id": SalesforceField<
        string,
        {
          readonly salesforceType: "id";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly aggregatable: true;
        }
      >;
      readonly "LastName": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly aggregatable: true;
        }
      >;
    },
    {
      readonly "Account": SalesforceParentRelationship<
        "Account",
        "AccountId",
        true
      >;
    },
    {
      readonly "Tasks": SalesforceChildRelationship<
        "Task",
        "WhoId"
      >;
    },
    never,
    Record<string, never>,
    boolean,
    "none",
    false
  >;
  readonly "Task": SalesforceObject<
    {
      readonly "Id": SalesforceField<
        string,
        {
          readonly salesforceType: "id";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly aggregatable: true;
        }
      >;
      readonly "WhoId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "Contact" | "Lead";
          readonly relationshipName: "Who";
          readonly aggregatable: true;
          readonly polymorphic: true;
        }
      >;
    },
    {
      readonly "Who": SalesforceParentRelationship<
        "Contact" | "Lead",
        "WhoId",
        true
      >;
    },
    Record<string, never>,
    never,
    Record<string, never>,
    boolean,
    "none",
    false
  >;
  readonly "User": SalesforceObject<
    {
      readonly "Id": SalesforceField<
        string,
        {
          readonly salesforceType: "id";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly aggregatable: true;
        }
      >;
      readonly "Name": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly aggregatable: true;
        }
      >;
    },
    Record<string, never>,
    Record<string, never>,
    never,
    Record<string, never>,
    boolean,
    "none"
  >;
}
