// This file is generated by @kysoql/codegen. Do not edit manually.

import type {
  SalesforceChildRelationship,
  SalesforceField,
  SalesforceObject,
  SalesforceParentRelationship,
} from "@kysoql/core";

export interface SalesforceSchema {
  readonly "Account": SalesforceObject<
    {
      readonly "AccountNumber": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "AccountSource": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Other" | "Partner Referral" | "Phone Inquiry" | "Purchased List" | "Web";
        }
      >;
      readonly "AnnualRevenue": SalesforceField<
        number,
        {
          readonly salesforceType: "currency";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "BillingAddress": SalesforceField<
        unknown,
        {
          readonly salesforceType: "address";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: false;
          readonly groupable: false;
        }
      >;
      readonly "BillingCity": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "BillingCountry": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "BillingGeocodeAccuracy": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Address" | "Block" | "City" | "County" | "ExtendedZip" | "NearAddress" | "Neighborhood" | "State" | "Street" | "Unknown" | "Zip";
        }
      >;
      readonly "BillingLatitude": SalesforceField<
        number,
        {
          readonly salesforceType: "double";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "BillingLongitude": SalesforceField<
        number,
        {
          readonly salesforceType: "double";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "BillingPostalCode": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "BillingState": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "BillingStreet": SalesforceField<
        string,
        {
          readonly salesforceType: "textarea";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "CleanStatus": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Acknowledged" | "Different" | "Inactive" | "Matched" | "NotFound" | "Pending" | "SelectMatch" | "Skipped";
        }
      >;
      readonly "CreatedById": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "User";
          readonly relationshipName: "CreatedBy";
        }
      >;
      readonly "CreatedDate": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "DandbCompanyId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "DandBCompany";
          readonly relationshipName: "DandbCompany";
        }
      >;
      readonly "Description": SalesforceField<
        string,
        {
          readonly salesforceType: "textarea";
          readonly nullable: true;
          readonly filterable: false;
          readonly sortable: false;
          readonly groupable: false;
        }
      >;
      readonly "DunsNumber": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Fax": SalesforceField<
        string,
        {
          readonly salesforceType: "phone";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Id": SalesforceField<
        string,
        {
          readonly salesforceType: "id";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Industry": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Agriculture" | "Apparel" | "Banking" | "Biotechnology" | "Chemicals" | "Communications" | "Construction" | "Consulting" | "Education" | "Electronics" | "Energy" | "Engineering" | "Entertainment" | "Environmental" | "Finance" | "Food & Beverage" | "Government" | "Healthcare" | "Hospitality" | "Insurance" | "Machinery" | "Manufacturing" | "Media" | "Not For Profit" | "Other" | "Recreation" | "Retail" | "Shipping" | "Technology" | "Telecommunications" | "Transportation" | "Utilities";
        }
      >;
      readonly "IsDeleted": SalesforceField<
        boolean,
        {
          readonly salesforceType: "boolean";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Jigsaw": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "JigsawCompanyId": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly relationshipName: "JigsawCompany";
        }
      >;
      readonly "LastActivityDate": SalesforceField<
        string,
        {
          readonly salesforceType: "date";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "LastModifiedById": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "User";
          readonly relationshipName: "LastModifiedBy";
        }
      >;
      readonly "LastModifiedDate": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "LastReferencedDate": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "LastViewedDate": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "MasterRecordId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "Account";
          readonly relationshipName: "MasterRecord";
        }
      >;
      readonly "NaicsCode": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "NaicsDesc": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Name": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "NumberOfEmployees": SalesforceField<
        number,
        {
          readonly salesforceType: "int";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "OperatingHoursId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "OperatingHours";
          readonly relationshipName: "OperatingHours";
        }
      >;
      readonly "OwnerId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "User";
          readonly relationshipName: "Owner";
        }
      >;
      readonly "Ownership": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Other" | "Private" | "Public" | "Subsidiary";
        }
      >;
      readonly "ParentId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "Account";
          readonly relationshipName: "Parent";
        }
      >;
      readonly "Phone": SalesforceField<
        string,
        {
          readonly salesforceType: "phone";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "PhotoUrl": SalesforceField<
        string,
        {
          readonly salesforceType: "url";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Rating": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Cold" | "Hot" | "Warm";
        }
      >;
      readonly "ShippingAddress": SalesforceField<
        unknown,
        {
          readonly salesforceType: "address";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: false;
          readonly groupable: false;
        }
      >;
      readonly "ShippingCity": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "ShippingCountry": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "ShippingGeocodeAccuracy": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Address" | "Block" | "City" | "County" | "ExtendedZip" | "NearAddress" | "Neighborhood" | "State" | "Street" | "Unknown" | "Zip";
        }
      >;
      readonly "ShippingLatitude": SalesforceField<
        number,
        {
          readonly salesforceType: "double";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "ShippingLongitude": SalesforceField<
        number,
        {
          readonly salesforceType: "double";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "ShippingPostalCode": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "ShippingState": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "ShippingStreet": SalesforceField<
        string,
        {
          readonly salesforceType: "textarea";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Sic": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "SicDesc": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Site": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "SystemModstamp": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "TickerSymbol": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Tradestyle": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Type": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Channel Partner / Reseller" | "Customer - Channel" | "Customer - Direct" | "Installation Partner" | "Other" | "Prospect" | "Technology Partner";
        }
      >;
      readonly "Website": SalesforceField<
        string,
        {
          readonly salesforceType: "url";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "YearStarted": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
    },
    {
      readonly "CreatedBy": SalesforceParentRelationship<
        "User",
        "CreatedById",
        false
      >;
      readonly "DandbCompany": SalesforceParentRelationship<
        "DandBCompany",
        "DandbCompanyId",
        true
      >;
      readonly "LastModifiedBy": SalesforceParentRelationship<
        "User",
        "LastModifiedById",
        false
      >;
      readonly "MasterRecord": SalesforceParentRelationship<
        "Account",
        "MasterRecordId",
        true
      >;
      readonly "OperatingHours": SalesforceParentRelationship<
        "OperatingHours",
        "OperatingHoursId",
        true
      >;
      readonly "Owner": SalesforceParentRelationship<
        "User",
        "OwnerId",
        false
      >;
      readonly "Parent": SalesforceParentRelationship<
        "Account",
        "ParentId",
        true
      >;
    },
    {
      readonly "AccountCleanInfos": SalesforceChildRelationship<
        "AccountCleanInfo",
        "AccountId"
      >;
      readonly "AccountContactRoles": SalesforceChildRelationship<
        "AccountContactRole",
        "AccountId"
      >;
      readonly "AccountPartnersFrom": SalesforceChildRelationship<
        "AccountPartner",
        "AccountFromId"
      >;
      readonly "AccountPartnersTo": SalesforceChildRelationship<
        "AccountPartner",
        "AccountToId"
      >;
      readonly "ActivityHistories": SalesforceChildRelationship<
        "ActivityHistory",
        "AccountId"
      >;
      readonly "Assets": SalesforceChildRelationship<
        "Asset",
        "AccountId"
      >;
      readonly "AssociatedLocations": SalesforceChildRelationship<
        "AssociatedLocation",
        "ParentRecordId"
      >;
      readonly "AttachedContentDocuments": SalesforceChildRelationship<
        "AttachedContentDocument",
        "LinkedEntityId"
      >;
      readonly "Attachments": SalesforceChildRelationship<
        "Attachment",
        "ParentId"
      >;
      readonly "AuthorizationFormConsents": SalesforceChildRelationship<
        "AuthorizationFormConsent",
        "ConsentGiverId"
      >;
      readonly "CardPaymentMethods": SalesforceChildRelationship<
        "CardPaymentMethod",
        "AccountId"
      >;
      readonly "Cases": SalesforceChildRelationship<
        "Case",
        "AccountId"
      >;
      readonly "ChildAccounts": SalesforceChildRelationship<
        "Account",
        "ParentId"
      >;
      readonly "CombinedAttachments": SalesforceChildRelationship<
        "CombinedAttachment",
        "ParentId"
      >;
      readonly "CommSubscriptionConsents": SalesforceChildRelationship<
        "CommSubscriptionConsent",
        "ConsentGiverId"
      >;
      readonly "ContactPointAddresses": SalesforceChildRelationship<
        "ContactPointAddress",
        "ParentId"
      >;
      readonly "ContactPointEmails": SalesforceChildRelationship<
        "ContactPointEmail",
        "ParentId"
      >;
      readonly "ContactPointPhones": SalesforceChildRelationship<
        "ContactPointPhone",
        "ParentId"
      >;
      readonly "ContactRequests": SalesforceChildRelationship<
        "ContactRequest",
        "WhatId"
      >;
      readonly "Contacts": SalesforceChildRelationship<
        "Contact",
        "AccountId"
      >;
      readonly "ContentDocumentLinks": SalesforceChildRelationship<
        "ContentDocumentLink",
        "LinkedEntityId"
      >;
      readonly "Contracts": SalesforceChildRelationship<
        "Contract",
        "AccountId"
      >;
      readonly "CreditMemos": SalesforceChildRelationship<
        "CreditMemo",
        "BillingAccountId"
      >;
      readonly "DigitalWallets": SalesforceChildRelationship<
        "DigitalWallet",
        "AccountId"
      >;
      readonly "DuplicateRecordItems": SalesforceChildRelationship<
        "DuplicateRecordItem",
        "RecordId"
      >;
      readonly "Emails": SalesforceChildRelationship<
        "EmailMessage",
        "RelatedToId"
      >;
      readonly "Entitlements": SalesforceChildRelationship<
        "Entitlement",
        "AccountId"
      >;
      readonly "Events": SalesforceChildRelationship<
        "Event",
        "WhatId"
      >;
      readonly "Expenses": SalesforceChildRelationship<
        "Expense",
        "AccountId"
      >;
      readonly "Feeds": SalesforceChildRelationship<
        "AccountFeed",
        "ParentId"
      >;
      readonly "FeedSubscriptionsForEntity": SalesforceChildRelationship<
        "EntitySubscription",
        "ParentId"
      >;
      readonly "FinanceBalanceSnapshots": SalesforceChildRelationship<
        "FinanceBalanceSnapshot",
        "AccountId"
      >;
      readonly "FinanceTransactions": SalesforceChildRelationship<
        "FinanceTransaction",
        "AccountId"
      >;
      readonly "Histories": SalesforceChildRelationship<
        "AccountHistory",
        "AccountId"
      >;
      readonly "Invoices": SalesforceChildRelationship<
        "Invoice",
        "BillingAccountId"
      >;
      readonly "Kysoql_Records__r": SalesforceChildRelationship<
        "Kysoql_Record__c",
        "Account__c"
      >;
      readonly "MaintenancePlans": SalesforceChildRelationship<
        "MaintenancePlan",
        "AccountId"
      >;
      readonly "MessagingEndUsers": SalesforceChildRelationship<
        "MessagingEndUser",
        "AccountId"
      >;
      readonly "MessagingSessions": SalesforceChildRelationship<
        "MessagingSession",
        "EndUserAccountId"
      >;
      readonly "Notes": SalesforceChildRelationship<
        "Note",
        "ParentId"
      >;
      readonly "NotesAndAttachments": SalesforceChildRelationship<
        "NoteAndAttachment",
        "ParentId"
      >;
      readonly "OpenActivities": SalesforceChildRelationship<
        "OpenActivity",
        "AccountId"
      >;
      readonly "Opportunities": SalesforceChildRelationship<
        "Opportunity",
        "AccountId"
      >;
      readonly "OpportunityPartnersTo": SalesforceChildRelationship<
        "OpportunityPartner",
        "AccountToId"
      >;
      readonly "Orders": SalesforceChildRelationship<
        "Order",
        "AccountId"
      >;
      readonly "PartnersFrom": SalesforceChildRelationship<
        "Partner",
        "AccountFromId"
      >;
      readonly "PartnersTo": SalesforceChildRelationship<
        "Partner",
        "AccountToId"
      >;
      readonly "PaymentAuthorizations": SalesforceChildRelationship<
        "PaymentAuthorization",
        "AccountId"
      >;
      readonly "PaymentLinesInvoice": SalesforceChildRelationship<
        "PaymentLineInvoice",
        "AssociatedAccountId"
      >;
      readonly "Payments": SalesforceChildRelationship<
        "Payment",
        "AccountId"
      >;
      readonly "ProcessInstances": SalesforceChildRelationship<
        "ProcessInstance",
        "TargetObjectId"
      >;
      readonly "ProcessSteps": SalesforceChildRelationship<
        "ProcessInstanceHistory",
        "TargetObjectId"
      >;
      readonly "ProductRequestLineItems": SalesforceChildRelationship<
        "ProductRequestLineItem",
        "AccountId"
      >;
      readonly "ProductRequests": SalesforceChildRelationship<
        "ProductRequest",
        "AccountId"
      >;
      readonly "ProvidedAssets": SalesforceChildRelationship<
        "Asset",
        "AssetProvidedById"
      >;
      readonly "RecordActionHistories": SalesforceChildRelationship<
        "RecordActionHistory",
        "ParentRecordId"
      >;
      readonly "RecordActions": SalesforceChildRelationship<
        "RecordAction",
        "RecordId"
      >;
      readonly "RecordAssociatedGroups": SalesforceChildRelationship<
        "CollaborationGroupRecord",
        "RecordId"
      >;
      readonly "RefundLinePayments": SalesforceChildRelationship<
        "RefundLinePayment",
        "AssociatedAccountId"
      >;
      readonly "Refunds": SalesforceChildRelationship<
        "Refund",
        "AccountId"
      >;
      readonly "RelatedAuthorizationFormConsents": SalesforceChildRelationship<
        "AuthorizationFormConsent",
        "RelatedRecordId"
      >;
      readonly "ResourcePreferences": SalesforceChildRelationship<
        "ResourcePreference",
        "RelatedRecordId"
      >;
      readonly "ReturnOrders": SalesforceChildRelationship<
        "ReturnOrder",
        "AccountId"
      >;
      readonly "ServiceAppointmentAccount": SalesforceChildRelationship<
        "ServiceAppointment",
        "AccountId"
      >;
      readonly "ServiceAppointments": SalesforceChildRelationship<
        "ServiceAppointment",
        "ParentRecordId"
      >;
      readonly "ServiceContracts": SalesforceChildRelationship<
        "ServiceContract",
        "AccountId"
      >;
      readonly "ServicedAssets": SalesforceChildRelationship<
        "Asset",
        "AssetServicedById"
      >;
      readonly "ServiceResources": SalesforceChildRelationship<
        "ServiceResource",
        "AccountId"
      >;
      readonly "Shares": SalesforceChildRelationship<
        "AccountShare",
        "AccountId"
      >;
      readonly "Tasks": SalesforceChildRelationship<
        "Task",
        "WhatId"
      >;
      readonly "TopicAssignments": SalesforceChildRelationship<
        "TopicAssignment",
        "EntityId"
      >;
      readonly "Users": SalesforceChildRelationship<
        "User",
        "AccountId"
      >;
      readonly "WorkOrders": SalesforceChildRelationship<
        "WorkOrder",
        "AccountId"
      >;
    }
  >;
  readonly "Kysoql_Record__c": SalesforceObject<
    {
      readonly "Account__c": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "Account";
          readonly relationshipName: "Account__r";
        }
      >;
      readonly "Active__c": SalesforceField<
        boolean,
        {
          readonly salesforceType: "boolean";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Amount__c": SalesforceField<
        number,
        {
          readonly salesforceType: "double";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "Category__c": SalesforceField<
        string,
        {
          readonly salesforceType: "picklist";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly activePicklistValue: "Alpha" | "Beta" | "Gamma";
        }
      >;
      readonly "CreatedById": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "User";
          readonly relationshipName: "CreatedBy";
        }
      >;
      readonly "CreatedDate": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "External_Id__c": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Id": SalesforceField<
        string,
        {
          readonly salesforceType: "id";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "IsDeleted": SalesforceField<
        boolean,
        {
          readonly salesforceType: "boolean";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "LastModifiedById": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "User";
          readonly relationshipName: "LastModifiedBy";
        }
      >;
      readonly "LastModifiedDate": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
      readonly "Name": SalesforceField<
        string,
        {
          readonly salesforceType: "string";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "Occurred_On__c": SalesforceField<
        string,
        {
          readonly salesforceType: "date";
          readonly nullable: true;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
        }
      >;
      readonly "OwnerId": SalesforceField<
        string,
        {
          readonly salesforceType: "reference";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: true;
          readonly referenceTo: "Group" | "User";
          readonly relationshipName: "Owner";
        }
      >;
      readonly "SystemModstamp": SalesforceField<
        string,
        {
          readonly salesforceType: "datetime";
          readonly nullable: false;
          readonly filterable: true;
          readonly sortable: true;
          readonly groupable: false;
        }
      >;
    },
    {
      readonly "Account__r": SalesforceParentRelationship<
        "Account",
        "Account__c",
        true
      >;
      readonly "CreatedBy": SalesforceParentRelationship<
        "User",
        "CreatedById",
        false
      >;
      readonly "LastModifiedBy": SalesforceParentRelationship<
        "User",
        "LastModifiedById",
        false
      >;
      readonly "Owner": SalesforceParentRelationship<
        "Group" | "User",
        "OwnerId",
        false
      >;
    },
    {
      readonly "AttachedContentDocuments": SalesforceChildRelationship<
        "AttachedContentDocument",
        "LinkedEntityId"
      >;
      readonly "Attachments": SalesforceChildRelationship<
        "Attachment",
        "ParentId"
      >;
      readonly "CombinedAttachments": SalesforceChildRelationship<
        "CombinedAttachment",
        "ParentId"
      >;
      readonly "ContactRequests": SalesforceChildRelationship<
        "ContactRequest",
        "WhatId"
      >;
      readonly "ContentDocumentLinks": SalesforceChildRelationship<
        "ContentDocumentLink",
        "LinkedEntityId"
      >;
      readonly "DestinationFinanceTransactions": SalesforceChildRelationship<
        "FinanceTransaction",
        "DestinationEntityId"
      >;
      readonly "DuplicateRecordItems": SalesforceChildRelationship<
        "DuplicateRecordItem",
        "RecordId"
      >;
      readonly "FeedSubscriptionsForEntity": SalesforceChildRelationship<
        "EntitySubscription",
        "ParentId"
      >;
      readonly "FinanceBalanceSnapshots":
        | SalesforceChildRelationship<
            "FinanceBalanceSnapshot",
            "LegalEntityId"
          >
        | SalesforceChildRelationship<
            "FinanceBalanceSnapshot",
            "ReferenceEntityId"
          >;
      readonly "FinanceTransactions":
        | SalesforceChildRelationship<
            "FinanceTransaction",
            "LegalEntityId"
          >
        | SalesforceChildRelationship<
            "FinanceTransaction",
            "ReferenceEntityId"
          >;
      readonly "Notes": SalesforceChildRelationship<
        "Note",
        "ParentId"
      >;
      readonly "NotesAndAttachments": SalesforceChildRelationship<
        "NoteAndAttachment",
        "ParentId"
      >;
      readonly "ParentFinanceTransactions": SalesforceChildRelationship<
        "FinanceTransaction",
        "ParentReferenceEntityId"
      >;
      readonly "ProcessExceptions": SalesforceChildRelationship<
        "ProcessException",
        "AttachedToId"
      >;
      readonly "ProcessInstances": SalesforceChildRelationship<
        "ProcessInstance",
        "TargetObjectId"
      >;
      readonly "ProcessSteps": SalesforceChildRelationship<
        "ProcessInstanceHistory",
        "TargetObjectId"
      >;
      readonly "RecordActionHistories": SalesforceChildRelationship<
        "RecordActionHistory",
        "ParentRecordId"
      >;
      readonly "RecordActions": SalesforceChildRelationship<
        "RecordAction",
        "RecordId"
      >;
      readonly "RecordAssociatedGroups": SalesforceChildRelationship<
        "CollaborationGroupRecord",
        "RecordId"
      >;
      readonly "Shares": SalesforceChildRelationship<
        "Kysoql_Record__Share",
        "ParentId"
      >;
      readonly "SourceFinanceTransactions": SalesforceChildRelationship<
        "FinanceTransaction",
        "SourceEntityId"
      >;
      readonly "TopicAssignments": SalesforceChildRelationship<
        "TopicAssignment",
        "EntityId"
      >;
    }
  >;
}
